### PR TITLE
New MPI_T Events tests and example

### PR DESCRIPTION
**Pull request by cchambreau**
Signed-off-by: Chris Chambreau <chambreau1@llnl.gov>

### CODE REVIEW

**Comment by hppritcha** [comment]
@cchambreau i'll give this a test run when I get back from holiday shutdown.

**Comment by cchambreau** [comment]
@hppritcha Successful testing will require several changes to PR #8057, which I hope to commit today.  I will add a comment here when the code for that PR has been updated.

**Comment by cchambreau** [comment]
@hppritcha I have pushed all changes to [PR #8057](https://github.com/open-mpi/ompi/pull/8057).  Several tests currently require running with the ob1 pml module.

**Comment by hppritcha** [comment]
@cchambreau I'm getting a segfault for ```events_source`` using the code at PR https://github.com/open-mpi/ompi/pull/8057

**Pull request merged**
